### ISSUE TITLE
Wither Pet "grows up" and becomes a normal Wither

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#579]
### What steps will reproduce the issue?

1. Summon the Wither Pet
2. Wait a bit

### What was supposed to happen?

The Wither should stay in "baby" form

### What happened instead?

The Wither Pet becomes "adult" and starts to fly around uncontrolled (Cannot be disabled through UC)
He destroys stuff...which is terrible (It destroyed the "Storage Room" of one of my Players -_-)

### What version of UltraCosmetics are you using? Do not say 'latest'.

2.6-DEV-b13

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)

### What plugins do you have installed?

Plugins (46): BetterConcrete, BetterTridents, BigDoors, Bookshelf, BreakingSlab, CommandCooldown, CustomEnderChest, DeluxeMenus, Duels, dynmap, Essentials, EssentialsChat, FlyPerms, GSit, Hat, HolographicDisplays, HoloMobHealth, HomeGUI, InteractionVisualizer, JoinRules, KittenForever, LightAPI, LinkedPortals, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NotTooExpensive, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, PlugManX (PlugMan), ProtocolLib, QuickShop, RealScoreboard, RotationWrench, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

Nope

### Additional information that could be helpful in fixing the problem

Nope

**Comment by datatags** [comment]
Does it take a consistent amount of time for the wither to "grow up"? Or roughly how long?

**Comment by datatags** [comment]
My guess is that the wither is getting unloaded since the player is so far away, which causes UC to lose track of it and cancel the code that's supposed to keep the wither small. But the code that prevents the wither from shooting operated differently, so it would continue working after the wither loads back in.

Could you try out [this build](https://github.com/iSach/UltraCosmetics/actions/runs/1838149001) and confirm it fixes the issue? (Download and unzip the artifact UltraCosmetics-dev.zip) I've changed it so that if a pet gets unloaded it's automatically deleted and unequipped (or at least that's the theory.) I've tested it on my server briefly with a wither and it seemed to work correctly.

(the build isn't finished as of this writing, it usually takes 30-40 minutes)

**Comment by Chris6ix** [comment]
I tested this build with the same random flying and teleporting and the issue seems to be gone.
The wither Pet despawned when out of render distance for a long time (Where he would "grow up" without this fix)
The only thing I noticed it that he now does [this](https://imgur.com/a/cxxShJx) when you fly out of his render distance and then touch the ground (He tries to fly back to the spot he was before being teleported to you)

So the fix you did works fine :)

**Comment by datatags** [comment]
That's really weird, are there any console errors? Maybe it's related to how the slime pet behaves?

Closing this since the issue was fixed :)

**Comment by Chris6ix** [comment]
> That's really weird, are there any console errors? Maybe it's related to how the slime pet behaves?

Nope, no Errors in console...
Yeah the Slime Pet does the same thing, but without actually being teleported (The Wither Pet seems to want to go back to its last spot, while the slime pet just starts to wander off as soon as its summoned...)
> Closing this since the issue was fixed :)

Sure :)
