### ISSUE TITLE
Option to enable/disable open treasurechest design

### ISSUE THREAD

**Issue by GameWatch21** [iSach/UltraCosmetics#600]
It's really a good design when player execute the `/uc treasurechest` and the block around them changed like altar

But, i think some other server want it to be very simple for player to open the treasurechest, where `/uc treasurechest` will open and their reward automatically sent to player's inventory

It will help player to open treasurechest anywhere they want, without waiting for it's surrounding to turn into altar and wait for the reward roll and That's all i suggest.

Thank you for creating this plugin

**Comment by datatags** [comment]
Hey, thanks for opening an issue for this. Do you have an idea of how you would like it to be activated? Like with a command?

**Comment by Chris6ix** [comment]
Hey, maybe I misunderstood, but is this not just `/uc reward`?

**Comment by datatags** [comment]
> Hey, maybe I misunderstood, but is this not just `/uc reward`?

Yes, but the difference is that `/UC reward` is not supposed to be user-facing, so it'd be nice to have a way for users to spend keys and get cosmetics without having structures like the treasure chests.

**Comment by Chris6ix** [comment]
Oh...I always thought that `/uc reward` was exactly the same as just opening a treasurechest but a lot faster by skipping basically everything (So also using a key)...

**Comment by datatags** [comment]
> Oh...I always thought that `/uc reward` was exactly the same as just opening a treasurechest but a lot faster by skipping basically everything (So also using a key)...

Ah, yeah `/uc reward` was actually created to spam a given number of rewards to help debug an issue where unlocked cosmetics weren't being issued correctly, so it doesn't do any key calculations or anything.

**Comment by Chris6ix** [comment]
Hmm okay...you maybe could add the Key calculations to `/uc reward` and just give yourself keys if you need to use the cmd for debugging? This would close this with a pretty easy change, or am I wrong?

**Comment by datatags** [comment]
Maybe, the problem though would be how to handle giving just one reward, for example (or any number that's not divisible by rewards per key.) Since UC normally gives 4 rewards per key, and we can't really take a quarter of a key, what should it do?

I'm thinking the `/uc reward` command is probably good how it is, to allow for using it in other plugins' loot crates or whatever without needing to care about keys. The code for `/uc reward` is already pretty simple so adding another command that just rewards the player however many times specified in config and takes a key shouldn't be too difficult.

One thing I'm wondering though is whether it needs to have a GUI button, like you right click instead of left click on the "open a treasure chest" button to do a fast reward like that.

**Comment by Chris6ix** [comment]
I like the last idea through the GUI, but it should be configurable or have permissions attached to it so that a server owner can decide if he wants to only use the "normal" method, only the "quick" method or both...

If we make it like that, then there is not even a need for a specialised command imo

**Comment by datatags** [comment]
Yeah true. I'll probably look at adding this after 2.6.3 is released since 1.19 comes out tomorrow.

**Comment by Chris6ix** [comment]
Sure!
I also thought about adding the Warden, Frog and Allay as pets to UC and changing the Goat's Item from Wheat to the Goat Horn now that it's out :)

**Comment by GameWatch21** [comment]
> Hey, thanks for opening an issue for this. Do you have an idea of how you would like it to be activated? Like with a command?

I think enable and disable it at config file is enough, like flipping the true/false statement for spawning the structure when the command executed

**Comment by datatags** [comment]
I think I'll just do a config option and a permission then, and have it accessible through the GUI.

Thanks for the suggestions, I'll keep you updated on how that goes 😄
