### ISSUE TITLE
Customizable main menu

### ISSUE THREAD

**Issue by datatags** [iSach/UltraCosmetics#608]
### Describe the feature and how it would be used

A new config section (or config file?), custom main menu. You can set slots for built-in buttons (such as the Morphs menu button or the clear cosmetics button) and custom buttons that run command(s) when you click them.

When not enabled, the main menu would still be the one UC generates by default.

### Are there alternatives?

This would be a better alternative to the existing `Back-To-Main-Menu-Command` that some servers are currently using to get a custom main menu.

**Comment by dennishzg** [comment]
I like this feature but can we keep the `Back-To-Main-Menu-Command` for "advanced" users who want to build a fully custom menu with DeluxeMenus for example? I prefer the current solution because all my custom menu files are in one place, and i can use all the DeluxeMenus features like "[Requirements](https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/requirements)".
This feature is great for people who want a quick and easy custom menu.

**Comment by datatags** [comment]
Yes, I'm planning on keeping both

**Comment by datatags** [comment]
Done in UC 3.2
